# Copyright 2011 by the Manoc Team
#
# This library is free software. You can redistribute it and/or modify
# it under the same terms as Perl itself.
package Manoc::Model::ManocDB;

use strict;
use base 'Catalyst::Model::DBIC::Schema';

__PACKAGE__->config(
    schema_class => 'Manoc::DB',

);

=head1 NAME

Manoc::Model::ManocDB - Catalyst DBIC Schema Model

=head1 SYNOPSIS

See L<Manoc>

=head1 DESCRIPTION

L<Catalyst::Model::DBIC::Schema> Model using schema L<Manoc::DB>

=head1 GENERATED BY

Catalyst::Helper::Model::DBIC::Schema - 0.4

=head1 AUTHOR

gabriele

=head1 LICENSE

This library is free software, you can redistribute it and/or modify
it under the same terms as Perl itself.

=cut

1;
