requires 'Catalyst::Runtime', '5.90077';
requires 'Catalyst::Plugin::ConfigLoader';
requires 'Catalyst::Plugin::Static::Simple';
requires 'Catalyst::Action::RenderView';
requires 'Catalyst::Plugin::StackTrace';
requires 'Catalyst::Plugin::Session';
requires 'Catalyst::Plugin::Session::Store::DBI';
requires 'Catalyst::Plugin::Scheduler';
requires 'Catalyst::Plugin::Session::State::Cookie';
requires 'Catalyst::Plugin::Authorization::ACL', '== 0.15';
requires 'Catalyst::Authentication::Store::DBIx::Class';
requires 'Config::General';
requires 'DBI';
requires 'DBIx::Class::EncodedColumn';
requires 'HTML::FormHandler', '0.32002';
requires 'Log::Log4perl';
requires 'Moose';
requires 'MooseX::Types::IPv4';
requires 'namespace::autoclean';
requires 'Net::Pcap';
requires 'NetPacket', '== 1.4.2';
requires 'Regexp::Common';
