requires 'Module::Runtime';
requires 'Moose';
requires 'namespace::autoclean';
requires 'Log::Log4perl', '1.46';
requires 'DBI';
requires 'DBIx::Class';
requires 'DBIx::Class::EncodedColumn';
requires 'Catalyst::Runtime', '5.90077';
requires 'Catalyst::Authentication::Credential::HTTP';
requires 'Catalyst::Plugin::ConfigLoader';
requires 'Catalyst::Plugin::Static::Simple';
requires 'Catalyst::Action::RenderView';
requires 'Catalyst::Plugin::StackTrace';
requires 'Catalyst::Plugin::Session';
requires 'Catalyst::Plugin::Session::Store::DBI';
requires 'Catalyst::Plugin::Scheduler';
requires 'Catalyst::Plugin::Session::State::Cookie';
requires 'Catalyst::Plugin::Authorization::ACL';
requires 'Catalyst::Plugin::Authorization::Roles';
requires 'Catalyst::Authentication::Store::DBIx::Class';
requires 'Catalyst::View::TT';
requires 'Catalyst::View::JSON';
requires 'Config::General';
requires 'HTML::FormHandler';
requires 'HTML::FormHandler::Model::DBIC';
requires 'MooseX::Types::IPv4';
requires 'MooseX::Storage';
requires 'Net::Pcap';
requires 'NetPacket';
requires 'Regexp::Common';
requires 'YAML::Syck';
requires 'Config::JFDI';
requires 'SQL::Translator';
#requires 'SNMP::Info';

