---
- name: Manoc | Create a new database
  mysql_db: name={{manoc_db_name}} state=present

- name: Manoc | Create DB user
  mysql_user:
    name: "{{manoc_db_user}}"
    password: "{{manoc_db_pass}}"
    priv: "{{manoc_db_name}}.*:ALL,GRANT"
    state: present

- name: Manoc | Install perl vendor packages and other prereqs
  yum: name={{item}} state=present
  with_items:
    - perl-core
    - perl-devel
    - gcc
    - perl-DBD-MySQL
    - net-snmp-perl
    - libpcap-devel

- name: Manoc | Test for cpanm
  shell: perl -MApp::cpanminus -e1
  register: cpanm_result
  ignore_errors: true

- name: Manoc | download CPANm installer
  get_url:
    url: http://cpanmin.us
    dest: /tmp/cpanmin.pl
    force: no
  when: cpanm_result|failed

- name: Manoc | Install CPANm
  shell: perl /tmp/cpanmin.pl App::cpanminus
  when: cpanm_result|failed

- name: Manoc | Install Manoc deps
  environment:
      PATH: "{{ ansible_env.PATH }}:/usr/local/bin"
      PERL_CPANM_OPT: "--recommends"
  cpanm:
      installdeps: true
      from_path: "{{manoc_home}}"
      notest: True
      locallib: "{{manoc_local_lib}}"

- name: Manoc | Create profile file for local::lib
  shell: "perl -Mlocal::lib={{manoc_local_lib}} > /etc/profile.d/manoc_lib.sh"
  args:
      creates: "/etc/profile.d/manoc_lib.sh"

- name:  Manoc | Install additional deps
  environment:
      PATH: "{{ ansible_env.PATH }}:/usr/local/bin"
  cpanm:
      name: "{{item}}"
      notest: True
      locallib: "{{manoc_local_lib}}"
  with_items:
      - FCGI::ProcManager
      - Net::Pcap
      - NetPacket::Ethernet
      - DBD::mysql

- name: Manoc | Create helper script for vagrant user
  template: src=manoc_init_db.sh dest=/usr/local/bin mode=755 

- name: Manoc | Create manoc config file
  template: src=manoc.conf dest=/etc mode=644

- name: Manoc | Create manoc log config file
  template: src=manoc_log.conf dest=/etc mode=644

- name: Manoc | Create run dir
  file:
    path: /var/run/manoc/
    state: directory
    mode: 0755

- name: Manoc | Create log dir
  file:
    path: /var/log/manoc/
    state: directory
    mode: 0755

- name: Manoc | Create Systemd Unit files
  template: src=manoc-{{item}}.service dest=/lib/systemd/system/ mode=644
  with_items:
      - arpsniffer
      - fcgi
      - netwalker
  notify:
    - reload systemctl

- name: Manoc | Start manoc WebApp
  service: name=manoc-{{item}}.service state=started enabled=yes
  with_items:
      - arpsniffer
      - fcgi
      - netwalker
