name: perltidy
on:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'
  pull_request:

jobs:
  perltidy:
    runs-on: ubuntu-latest
    container:
      image: perl:5.32
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: cpanm -n Perl::Tidy
      - name: perltidy --version
        run: perltidy --version
      - name: Run perltidy
        shell: bash
        run: |
          shopt -s extglob globstar nullglob
          perltidy --pro=.../.perltidyrc -b -bext='/' **/*.p[lm] **/*.t && git diff --exit-code
