name: Push time tests
on: [push]
jobs:
  run-prove:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: '5.34'
      - run: cpanm -n --installdeps .
      - run: prove -lv t
  perlcritic:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gmambro/action-perlcritic@master
        with:
          perlcritic_flags: --quiet --profile .perlcriticrc lib/ script/
